"""One-time bootstrap: write blend_cache.json from a hand-authored extraction.

These are Claude's extractions for the current catalog (the same thing extract.py
would get from the API), so the local cache is seeded for free. overrides.json
still wins over anything here. Future NEW titles get filled in by extract.py.

Value form: [brand, blend]  (is_tin defaults True)
            [brand, blend, false]  (variety/cigar/mixed lot — not one blend)
"""
import json
import os

HERE = os.path.dirname(__file__)
DOCS = os.path.join(HERE, "docs")
SRC = ["products.json", "products_tinbids.json",
       "products_treasuredsmokes.json", "products_4noggins.json"]

EXTRACT = {
  # ---------- pipestud ----------
  "McClelland’s Personal Reserve Series Blackwoods Flake 50g tin – Year 2016": ["McClelland", "Personal Reserve Blackwoods Flake"],
  "Mullingar’s Moyhall Oriental Blend 2oz tins – 1980’s or Early 1990’s Production": ["Mullingar", "Moyhall Oriental Blend"],
  "Dannemann’s Blend 600 in 50g tins – 1970’s era & Made by Germain (One Tin Per Customer)": ["Dannemann", "Blend 600"],
  "Mullingar’s Syr. Latakia Kenmare 2oz tin – 1980’s or 1990’s Production": ["Mullingar", "Syrian Latakia Kenmare"],
  "Dannemann’s Blend 500 in a 50g tin – 1970’s era & Made by Germain": ["Dannemann", "Blend 500"],
  "Dannemann’s Blend 700 in 50g tins – 1970’s era & Made by Germain (One Tin Per Customer)": ["Dannemann", "Blend 700"],
  "House of Craven Original Craven Mixture 50g tins – 1970’s era": ["House of Craven", "Craven Mixture"],
  "Robert McConnell’s Original Red Virginia 50g tin – Year 1998": ["Robert McConnell", "Red Virginia"],
  "JBR’s Quintessence Curly Cut 50g tin – 1990’s era & Made by Mac Baren’s": ["JBR", "Quintessence Curly Cut"],
  "Brindley’s English Mixture 1-3/4 oz tins – 1970’s era": ["Brindley", "English Mixture"],
  "Elephant & Castle New World 50g tin – 1980’s era and Made by McConnell’s in England": ["Elephant & Castle", "New World"],
  "G. Smith & Sons Virginia 50g tin – 1970’s era": ["G. Smith & Sons", "Virginia"],
  "W.O. Larsen No. 28 English Mixture 100g tin – 1980’s era and Made by Orlik": ["W.O. Larsen", "No. 28 English Mixture"],
  "Savinelli Punto Oro Cavendish 50g tins – 1980’s era and Made by Mac Baren": ["Savinelli", "Punto Oro Cavendish"],
  "Savinelli Mr. G Black Cavendish 50g tins – 1980’s era and Made by Mac Baren": ["Savinelli", "Mr. G Black Cavendish"],
  "Savinelli Special 50g tins – 1980’s era and Made by Mac Baren": ["Savinelli", "Special"],
  "Savinelli English Mixture 50g tins – 1980’s era and Made by Mac Baren": ["Savinelli", "English Mixture"],
  "McClelland’s Christmas Cheer 100g tin – Year 2017": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tins – Year 2015": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2016": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2014": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2013": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tins – Year 2011": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2012": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tins – Year 2010": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2009": ["McClelland", "Christmas Cheer"],
  "McClelland’s Christmas Cheer 100g tin – Year 2008": ["McClelland", "Christmas Cheer"],
  "Dunhill Elizabethan Mixture 50g tin – Year 2014": ["Dunhill", "Elizabethan Mixture"],
  "Dunhill Murray’s era Durbar 50g tin – Year 2014": ["Dunhill", "Durbar"],
  "Dunhill My Mixture 965 in a 50g tin – Year 2014": ["Dunhill", "My Mixture 965"],
  "Dunhill Nightcap 50g tin – Year 2014": ["Dunhill", "Nightcap"],
  "Dunhill Baby’s Bottom 50g tin – First Year 2015 Reintroduction": ["Dunhill", "Baby's Bottom"],
  "Sutliff  Variety 4-Pack Crumble Kake 50g tins – Years 2021 & 2022": ["Sutliff", "", False],
  "Golden Oldie Alert! Skandinavik Regular 6oz tin – 1980s era": ["Skandinavik", "Regular"],
  "Sutliff 3-Pack of Crumble Kake #4 in 50g tins – Year 2022": ["Sutliff", "Crumble Kake #4"],
  "Sutliff Cringle Flake Holiday Edition 3-Pack of 2oz tins – Year 2024 W/ McClelland’s Tobacco": ["Sutliff", "Cringle Flake"],
  "Sutliff Crumble Kake  Engllish #1 in a 5-Pack of 50g tins – Year 2022": ["Sutliff", "Crumble Kake English #1"],
  "McClelland’s Holiday Spirit 50g tins – Year 2016": ["McClelland", "Holiday Spirit"],
  "McClelland’s Holiday Spirit 50g tins – Year 2017": ["McClelland", "Holiday Spirit"],
  "McClelland’s Christmas Cheer 100g tins – Year 2017": ["McClelland", "Christmas Cheer"],
  "McClelland’s Best of Show 50g tins – Year 2015": ["McClelland", "Best of Show"],
  "McClelland’s The Mind Meld Chocolate Nut 50g tins – Year 2015": ["McClelland", "The Mind Meld Chocolate Nut"],
  "Samuel Gawith Full Virginia Flake 4-Pack of 50g tins – Year 2012": ["Samuel Gawith", "Full Virginia Flake"],
  "McClelland’s Frog Morton Cellar 100g tins – Second Year 2013 Production": ["McClelland", "Frog Morton's Cellar"],
  "Samuel Gawith St. James Flake 50g tin – Year 2012": ["Samuel Gawith", "St. James Flake"],
  "Samuel Gawith 1792 Flake 50g tins – Year 2012": ["Samuel Gawith", "1792 Flake"],
  "Fribourg & Treyer Blackjack 50g tins – Year 2014": ["Fribourg & Treyer", "Blackjack"],
  "Sillem’s Copenhagen Blend 50g tin – Year 2014": ["Sillem's", "Copenhagen Blend"],
  "G.L. Pease Classic Collection Charing Cross 2oz tin – First Year 2003 Production": ["G.L. Pease", "Charing Cross"],
  "McClelland’s Ashton Revival Series Brindle Flake 50g tin – Year 2010": ["Ashton", "Brindle Flake"],
  "McClelland’s Frog Morton On the Bayou 50g tins – First Year 2003 Production": ["McClelland", "Frog Morton on the Bayou"],
  "McClelland’s Butera’s Royal Vintage Golden Cake 50g tin – Year 2012": ["Butera", "Golden Cake"],
  "Orlik Dark Strong Kentucky 50g tin – Year 2015": ["Orlik", "Dark Strong Kentucky"],
  "Escudo Navy De Luxe 50g tin – First Year 2008 Orlik era": ["Escudo", "Navy De Luxe"],
  "Peterson’s Irish Flake 50g tins – Year 2010": ["Peterson", "Irish Flake"],
  "Mac Baren Latakia Blend Roll Cake 100g tin – Year 2004": ["Mac Baren", "Latakia Blend Roll Cake"],
  "Rattray’s Brown Clunee 100g tin – Year 2015": ["Rattray's", "Brown Clunee"],
  "Samuel Gawith Lakeland Dark 50g tin – Year 2017": ["Samuel Gawith", "Lakeland Dark"],
  "Rattray’s Marlin Flake 100g tin – Year 2009": ["Rattray's", "Marlin Flake"],
  "Rattray’s Old Gowrie 100g tin – Year 2009": ["Rattray's", "Old Gowrie"],
  "Rattray’s 3 Noggins 100g tin – Year 2009": ["Rattray's", "3 Noggins"],
  "Wellauer’s 100% Syr. Latakia 3-1/2oz tins – Year 2015": ["Wellauer's", "100% Syrian Latakia"],
  "Wessex Dark Flake 50g tins – Year 2012": ["Wessex", "Dark Flake"],
  "Wessex Dark Red Virginia Flake 50g tins – Year 2012": ["Wessex", "Dark Red Virginia Flake"],
  "Wessex Brown Virginia Flake 50g tins – Year 2012": ["Wessex", "Brown Virginia Flake"],
  "Wessex Curley Cut Virginia & Perique 50g tin – Years 2012": ["Wessex", "Curly Cut Virginia & Perique"],
  "Davidoff Royalty 50g tins – 1990’s era": ["Davidoff", "Royalty"],
  "Dannemann’s Blend 500 in a 50g tin – 1970’s era & Made by Germain (Lot #2)": ["Dannemann", "Blend 500"],
  "Dannemann’s Blend 700 in a 50g tin – 1970’s era & Made by Germain (Lot #2)": ["Dannemann", "Blend 700"],
  "Robert McConnell’s 100% Pure Syr. Latakia 50g tin – Year 2012": ["Robert McConnell", "100% Pure Syrian Latakia"],
  "Van Rossem’s Schippers Tabak 3-1/2oz Dented tin – 1970’s – 1980’s era (Lot #2)": ["Van Rossem", "Schippers Tabak"],
  "Bell’s Original W.D & H.O. Wills Scotland Made Three Nuns – 100g tin – 1980’s era": ["", "Three Nuns"],
  "McClelland’s Limited Edition Uncle Ed’s Scottish Mixture 50g tin – Year 1997": ["McClelland", "Uncle Ed's Scottish Mixture"],
  "Robert McConnell’s Original Oriental 50g tins – Year 1992": ["Robert McConnell", "Oriental"],
  "Lane Limited’s Original Crown Achievement 2oz tins – 1980’s era": ["Lane Limited", "Crown Achievement"],
  "Samuel Gawith Commonwealth 50g tins – Year 2013": ["Samuel Gawith", "Commonwealth Mixture"],
  "Robert Lewis Tree Mixture 50g tins – Year 2005": ["Robert Lewis", "Tree Mixture"],
  "Mac Baren Dark Twist Roll Cake One Pound tins – Year 2009": ["Mac Baren", "Dark Twist Roll Cake"],
  "Mac Baren Dark Twist Roll Cake 100g tins – Year 2009": ["Mac Baren", "Dark Twist Roll Cake"],
  "Van Rossem’s Schippers Tabak 3-1/2oz tins – 1070’s – 1980’s era": ["Van Rossem", "Schippers Tabak"],
  "Theodorus Niemeyer Flying Dutchman 2oz tins – 1960’s – 1970’s era": ["Theodorus Niemeyer", "Flying Dutchman"],

  # ---------- tinbids ----------
  "Butera Pelican - Sealed tin": ["Butera", "Pelican"],
  "Esoterica Penzance - sealed tin": ["Esoterica", "Penzance"],
  "Germain B.K. Flake 2018 NR": ["J.F. Germain", "B.K. Flake"],
  "Germain Century 2016 NR": ["J.F. Germain", "Century"],
  "Germain ‘BRIDGE: Old Brown Flake 2017 NR": ["J.F. Germain", "Bridge Old Brown Flake"],
  "Germain King Charles Smoking Mixture 2015 NR": ["J.F. Germain", "King Charles Mixture"],
  "Germain Medium Flake 2015 NR": ["J.F. Germain", "Medium Flake"],
  "MacBaren Stockton Spun Cut Limited Edition 2020 NR": ["Mac Baren", "Stockton Spun Cut"],
  "John Cotton’s Smyrna 2016 NR": ["John Cotton's", "Smyrna"],
  "Dunhill My Mixture No. 965, c. 1954–1958 Sealed 4oz Knife-Lid Tin, Pressure-Bulging Late King George VI Era Survivor": ["Dunhill", "My Mixture 965"],
  "John Cotton’s Number 1 2016 NR": ["John Cotton's", "Number 1"],
  "John Cotton’s Numbers 1 & 2 2016 NR": ["John Cotton's", "Numbers 1 & 2"],
  "Esoterica Tilbury  8oz bag and 2oz Tin": ["Esoterica", "Tilbury", False],
  "3 Tins - Rattray's Stirling Flake - 2024 - 50g": ["Rattray's", "Stirling Flake"],
  "Rattray's Marlin Flake": ["Rattray's", "Marlin Flake"],
  "Vintage - Brigadier Black - Antietam - 8oz": ["Brigadier Black", "Antietam"],
  "Vintage 2017 - Lot of 5 Sealed Dunhill My Mixture": ["Dunhill", "My Mixture"],
  "Rattray's Black Virginia": ["Rattray's", "Black Virginia"],
  "Esoterica And so to bed": ["Esoterica", "And So to Bed"],
  "Peterson 4-Royal Yacht": ["Peterson", "Royal Yacht"],
  "CAO Flavours 4-Cherrybomb": ["CAO", "Cherrybomb"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl Fires on the Levee Mixture 2 oz’s from 2025": ["Cornell & Diehl", "Fires on the Levee"],
  "Mac Baren HH Acadian Perique": ["Mac Baren", "HH Acadian Perique"],
  "2025 Esoterica Tillbury": ["Esoterica", "Tilbury"],
  "Esoterica Penzance 8oz Sealed Bag - October 2019 - Climate Controlled Cellar Aged": ["Esoterica", "Penzance"],
  "Vintage RED RIBBON from McCranie’s 50g 3 Sealed Tins": ["McCranie's", "Red Ribbon"],
  "Sutliff Blend No. 5 (Sutliff Private Stock) 5 x 1.5 oz tins": ["Sutliff", "Blend No. 5"],
  "Esotericia Bag and Tins Bid or Buy Now": ["Esoterica", "", False],
  "Esoterica Tobacciana Prembroke 2 oz": ["Esoterica", "Pembroke"],
  "Esoterica Pembroke (2 oz)": ["Esoterica", "Pembroke"],
  "Esoterica Tilbury (2 oz)": ["Esoterica", "Tilbury"],
  "Nice Sealed Dunhill Three Years Matured Virginia 50g. Tin": ["Dunhill", "Three Years Matured Virginia"],
  "2024 - Solani Aged Burley Flake - 50g": ["Solani", "656 Aged Burley Flake"],
  "Peterson 3-Sherlock Holmes": ["Peterson", "Sherlock Holmes"],
  "Ravenwood Eleventh Day of Christmas Bid or Buy Now": ["Ravenwood", "Eleventh Day of Christmas"],
  "Drew Estates - Central Park Stroll (50g)": ["Drew Estate", "Central Park Stroll"],
  "2023 Robert McConnell Scottish Flake - 3 Tins NR BIN $95": ["Robert McConnell", "Scottish Flake"],
  "2017 Orlik Dark Strong Kentucky - 1 Tin NR BIN $90": ["Orlik", "Dark Strong Kentucky"],
  "Mac Baren Old Dark Fired - 5 Tins NR BIN $300": ["Mac Baren", "HH Old Dark Fired"],
  "2012 Mac Baren Old Dark Fired 3.5oz - 1 Tin NR $125": ["Mac Baren", "HH Old Dark Fired"],
  "Cornell & Diehl Fires on the Levee Small Batch - 5 Tins NR BIN $150": ["Cornell & Diehl", "Fires on the Levee"],
  "1994 McClelland's Butera Latakia No.1 -  NR BIN $110": ["Butera", "Latakia No. 1"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl Firebird Flake 2 oz’s from 2024": ["Cornell & Diehl", "Firebird Flake"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl “From Beyond” Mixture 2 oz’s from 2025": ["Cornell & Diehl", "From Beyond"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl Sun Bear Navy Cask Mixture 2 oz’s from 2025": ["Cornell & Diehl", "Sun Bear Navy Cask"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl The Beast Mixture 2 oz’s from 2025": ["Cornell & Diehl", "The Beast"],
  "Collectible Tobacco Sealed Tin Cornell & Diehl Warped:The Haunting Mixture 2oz’s from 2025": ["Cornell & Diehl", "The Haunting"],
  "Esoterica- Penzance 7.94 oz": ["Esoterica", "Penzance"],
  "Collectible John Cotton’s Creme 50g Pipe Tobacco Sealed Original Tin Out of Production": ["John Cotton's", "Creme"],
  "Peterson’s Dunhill Nightcap Sealed 50g Tin": ["Dunhill", "Nightcap"],
  "Collectible Ravenwood Hobbit Leaf Sealed 50g Tin Made in USA Spring 2026": ["Ravenwood", "Hobbit Leaf"],
  "Cornell & Diehl Eight State Burley - 5 Tins NR BIN $150": ["Cornell & Diehl", "Eight State Burley"],
  "McClelland 40th Anniversary - NR BIN $225": ["McClelland", "40th Anniversary"],
  "5 pack Erinmore Flake (50g) 2014-Factory Sealed": ["Erinmore", "Flake"],
  "Lot of 4 Very Nice Sealed Cascadia 1.76oz. Tins": ["", "Cascadia"],
  "Very Nice Sealed Germain's King Charles 50g. Tin": ["J.F. Germain", "King Charles Mixture"],
  "Very Nice Sealed Dunhill Standard Mixture Mellow 50g. Tin": ["Dunhill", "Standard Mixture Mellow"],
  "Very Nice Sealed Bengal Slice 1.75oz. Tin": ["Sutliff", "Bengal Slices"],
  "Very Nice Sealed Dunhill Ye Olde Signe 50g. Tin": ["Dunhill", "Ye Olde Signe"],
  "Very Nice 2022 G. L. Pease Union Square 2oz. Tin": ["G.L. Pease", "Union Square"],
  "Very Nice Sealed Dunhill Durbar Mixture 50g. Tin": ["Dunhill", "Durbar"],
  "Very Nice 2022 Drucquer & Sons Casbah Balkan Crumble Plug 100g. Tin": ["Drucquer & Sons", "Casbah"],
  "Sealed in Mason Jar Mac Baren's Scottish Mixture Pipe Tobacco": ["Mac Baren", "Scottish Mixture"],
  "Sealed in Jar Esoterica Margate Pipe Tobacco": ["Esoterica", "Margate"],
  "Sealed 2024 Samuel Gawith Balkan Flake Burnt Ends 8oz. Box": ["Samuel Gawith", "Balkan Flake"],
  "Nice 2006 Cornell & Diehl Star of the East 066 8oz. Tin": ["Cornell & Diehl", "Star of the East"],
  "Ziplock Sealed Mystic Moor 16oz. Bag of Tobacco": ["", "Mystic Moor"],
  "Lot of 2 Very Nice Sealed Cascadia Downwind 1.76oz. Tins": ["", "Cascadia Downwind"],
  "John Aylesbury Luxury Flake-2015": ["John Aylesbury", "Luxury Flake"],
  "Samuel Gawith Aromatic 3-Pack (2014 & 2015)": ["Samuel Gawith", "", False],
  "Samuel Gawith Flake Assortment 5 pack (2014)": ["Samuel Gawith", "", False],
  "50g Bengal Slices- A Sutliff Tobacco Blend From 2016!": ["Sutliff", "Bengal Slices"],
  "50g War Horse Ready Cut From 2016!": ["War Horse", "Ready Cut"],
  "50g Tin Of C&D Buffalo Soldier From 2014!": ["Cornell & Diehl", "Buffalo Soldier"],
  "50g Hearth & Home Ashcroft Estate From 2016!": ["Hearth & Home", "Ashcroft Estate"],
  "50g Hearth & Home Virginia Memory From 2016!": ["Hearth & Home", "Virginia Memory"],
  "McClelland No. 24 VIRGINIA - Sealed 100g Tin": ["McClelland", "No. 24 Virginia"],
  "Sutliff Alexander Bridge - lot of 2": ["Sutliff", "Alexander Bridge"],
  "2019 MAC BAREN HH OLD DARK FIRED PLUG CUT": ["Mac Baren", "HH Old Dark Fired Plug Cut"],
  "Excellent Sealed 2005 Esoterica Penzance 8oz. Pack": ["Esoterica", "Penzance"],
  "Very Nice Sealed 2012 McCranie's Red Flake Prime 2008 Red Virginia 50g. Tin": ["McCranie's", "Red Flake"],
  "Excellent Sealed 2011 Samuel Gawith Full Virginia Flake 50g. Tin": ["Samuel Gawith", "Full Virginia Flake"],
  "Very Nice Sealed 2012 Hearth & Home International Pipe Smoking Day 2012 50g. Tin": ["Hearth & Home", "International Pipe Smoking Day"],
  "Very Nice Sealed 2018 Dunhill De Luxe Navy Rolls 50g. Tin": ["Dunhill", "De Luxe Navy Rolls"],
  "Very Nice Sealed 2013 Butera Pelican English-Oriental 2oz. Tin": ["Butera", "Pelican"],
  "Vintage  aromatic !  Peterson Special Reserve 2008 100grams.": ["Peterson", "Special Reserve"],
  "War Horse Green": ["War Horse", "Green"],
  "- Vintage -25 Years Old - BELLS THREE NUNS 50g. None Nicer! Rare!": ["", "Three Nuns"],
  "* 2004 * Mick McQuaid Plug 50g.  Traditional Irish plug Tobacco.": ["Mick McQuaid", "Plug"],
  "2x Sutliff Molto Dolce Sealed 1.5oz Tins": ["Sutliff", "Molto Dolce"],
  "2013 JF Germain Rich Dark Flake 2.7 oz": ["J.F. Germain", "Rich Dark Flake"],
  "2018 Smoker’s Haven In-B-Tween Mixture": ["Smoker's Haven", "In-B-Tween Mixture"],
  "Excellent 2016 Reiner 71 (LGF) 100 grams": ["Reiner", "Long Golden Flake"],
  "Butera Pelican Smoking Mixture 2 oz’s Sealed Pipe Tobacco Tin 2003": ["Butera", "Pelican"],
  "Esoterica Tobacciana Butera’s Margate 8 oz. Sealed Pipe Tobacco Germain & Son, UK": ["Esoterica", "Margate"],
  "7.7oz/218g of Sutliff/Hearth & Home Larry's Blend From 2010!": ["Hearth & Home", "Larry's Blend"],
  "(2x) Seattle Pipe Club (Sutliff) - Mississippi River Rum Barrel Aged": ["Seattle Pipe Club", "Mississippi River Rum Barrel Aged"],
  "C&D: Steamworks (26) 2 Tins: BIN 60": ["Cornell & Diehl", "Steamworks"],
  "(3) Sutliff Cringle Flake  2021": ["Sutliff", "Cringle Flake"],
  "(3) Sutliff Cringle Flake  2020": ["Sutliff", "Cringle Flake"],
  "Sutliff Country Cork": ["Sutliff", "Country Cork"],
  "Peter Heinrichs Golden Sliced Bid or Buy Now": ["Peter Heinrichs", "Golden Sliced"],
  "2024 Robert McConnell Oriental  - 1 Tin NR BIN $30": ["Robert McConnell", "Oriental"],
  "Lot of 2 Excellent 2019 & 2020 Cornell & Diehl Kings Stride Warped Series Until the End 2oz. Tins": ["Cornell & Diehl", "Until the End"],
  "Very Nice Sealed 2018 Dunhill My Mixture 965 50g. Tin": ["Dunhill", "My Mixture 965"],
  "Lot of 2 Excellent Sealed 2021 Rattray's Black Mallory 100g. Tobacco Tins": ["Rattray's", "Black Mallory"],
  "Very Nice 2021 G. L. Pease Quiet Nights 2oz. Tin": ["G.L. Pease", "Quiet Nights"],
  "Lot of 2 Excellent Sealed 2020 Ashton Artisan's Blend 50g. Tins": ["Ashton", "Artisan's Blend"],
  "Excellent Sealed 2018 Dunhill Nightcap 50g. Tin": ["Dunhill", "Nightcap"],
  "Lot of 2 Excellent Sealed 2020 Original Navy Cut Capstan 50g. Tins": ["Capstan", "Original Navy Cut"],
  "Very Nice Sealed 2018 Dunhill My Mixture BB1938 50g. Tin": ["Dunhill", "My Mixture BB1938"],
  "Very Nice Sealed 2018 McClelland's 40th Anniversary 100g. Tin": ["McClelland", "40th Anniversary"],
  "Frog Morton Sealed Tin from 2017": ["McClelland", "Frog Morton"],
  "Sutliff Pipe Force Episode V": ["Sutliff", "Pipe Force Episode V"],
  "2013 Samuel Gawith St James Flake 8 oz-3day auction": ["Samuel Gawith", "St. James Flake"],
  "2020 Mac Baren Vanilla Roll Cake 3.5oz Tin": ["Mac Baren", "Vanilla Roll Cake"],
  "1998 McClelland Iwan Ries Anniversary Blend Gourmet English 50g. Tin": ["McClelland", "Iwan Ries Anniversary Blend"],
  "Half and Half 14oz. Tin": ["", "Half & Half"],

  # ---------- treasuredsmokes ----------
  "Dunhill Flake - 2012": ["Dunhill", "Flake"],
  "Limited Run - Cobblestone Plum Rum": ["Cobblestone", "Plum Rum"],
  "Brigadier Black - Bull Run - 2013!": ["Brigadier Black", "Bull Run"],
  "Brigadier Black - Gettysburg - 2013!": ["Brigadier Black", "Gettysburg"],
  "Brigadier Black - Alamo - 2013!": ["Brigadier Black", "Alamo"],
  "Brigadier Black - Sherman's March - 2013!": ["Brigadier Black", "Sherman's March"],
  "Rattray's - Hal O' Thy Wynd - 2011!": ["Rattray's", "Hal O' The Wynd"],
  "Drew Estate - Harvest on Hudson - 2011!": ["Drew Estate", "Harvest on Hudson"],
  "Cornell & Diehl - Opening Night - 2011!": ["Cornell & Diehl", "Opening Night"],
  "Golden Triangle - Paulina - 2011": ["Golden Triangle", "Paulina"],
  "Golden Triangle - Belmont - 2011": ["Golden Triangle", "Belmont"],
  "Golden Triangle - St. James Perique - 2011": ["Golden Triangle", "St. James Perique"],
  "Golden Triangle - South Vacherie - 2011": ["Golden Triangle", "South Vacherie"],
  "Golden Triangle - Grand Point - 2011": ["Golden Triangle", "Grand Point"],
  "Cornell & Diehl - Exhausted Rooster - 2009-10!": ["Cornell & Diehl", "Exhausted Rooster"],
  "Cornell & Diehl - Exhausted Rooster - 2011!": ["Cornell & Diehl", "Exhausted Rooster"],
  "Cornell & Diehl - Exhausted Rooster - 2009!": ["Cornell & Diehl", "Exhausted Rooster"],
  "G.L. Pease - Haddo's Delight - 2009!": ["G.L. Pease", "Haddo's Delight"],
  "G.L. Pease - Haddo's Delight - 2010!": ["G.L. Pease", "Haddo's Delight"],
  "G.L. Pease - JackKnife Plug - 2011!": ["G.L. Pease", "Jackknife Plug"],
  "G.L. Pease - Jack Knife Plug - 2010!": ["G.L. Pease", "Jackknife Plug"],
  "G.L. Pease - Fillmore - 2010!": ["G.L. Pease", "Fillmore"],
  "G.L. Pease - Fillmore - 2009!": ["G.L. Pease", "Fillmore"],
  "G.L. Pease - Fillmore - 2008! 8 Ounce Big Can": ["G.L. Pease", "Fillmore"],
  "G.L. Pease - Fillmore - 2008!": ["G.L. Pease", "Fillmore"],
  "John Cotton's - Double Pressed Virginia - 2020": ["John Cotton's", "Double Pressed Virginia"],
  "Red Ribbon - 2017!": ["McCranie's", "Red Ribbon"],
  "McClelland Full Balkan Reserve": ["McClelland", "Full Balkan Reserve"],
  "Villiger - Mid-Day - 2013!": ["Villiger", "Mid-Day"],
  "Stanwell - Melange - 2015!": ["Stanwell", "Melange"],
  "Sasieni - Balkan - 2018!": ["Sasieni", "Balkan"],
  "Samuel Gawith - Sam's Flake - 2017!": ["Samuel Gawith", "Sam's Flake"],
  "Samuel Gawith - Squadron Leader - 2017!": ["Samuel Gawith", "Squadron Leader"],
  "Samuel Gawith - 1792 Flake - 2018!": ["Samuel Gawith", "1792 Flake"],
  "Samuel Gawith - Balkan Flake - 2018!": ["Samuel Gawith", "Balkan Flake"],
  "Samuel Gawith - Grousemoor - 2016!": ["Samuel Gawith", "Grousemoor"],
  "Samuel Gawith - Perfection - 2018!": ["Samuel Gawith", "Perfection"],
  "Robert McConnell - Scottish Blend - 2017!": ["Robert McConnell", "Scottish Blend"],
  "Robert Lewis - Orcilla Mixture - 2017!": ["Robert Lewis", "Orcilla Mixture"],
  "Rattray's - Bagpiper's Dream - 2018!": ["Rattray's", "Bagpiper's Dream"],
  "Rattray's - Jock's Mixture - 2018!": ["Rattray's", "Jock's Mixture"],
  "Peterson - University Flake - 2017!": ["Peterson", "University Flake"],
  "Orlik - Mellow Mixture - 2017!": ["Orlik", "Mellow Mixture"],
  "McCranie's - Somerled - 2017!": ["McCranie's", "Somerled"],
  "McClelland's - Blending Latakia - 2001!": ["McClelland", "Blending Latakia"],
  "Hearth and Home - Classic Burley Kake - 2012 - 8 Ounce Can!": ["Hearth & Home", "Classic Burley Kake"],
  "Half & Half - Burley & Bright - 2012!": ["", "Half & Half"],
  "Gawith Hoggarth - Balkan Mixture": ["Gawith & Hoggarth", "Balkan Mixture"],
  "Gawith Hoggarth - Rum Flake - 2021": ["Gawith & Hoggarth", "Rum Flake"],
  "Friburg & Treyer - Cut Blended Plug - 2017": ["Fribourg & Treyer", "Cut Blended Plug"],
  "Cornell & Diehl - Billy Budd - 2017": ["Cornell & Diehl", "Billy Budd"],
  "BriarWorks - Country Lawyer - 2018": ["BriarWorks", "Country Lawyer"],
  "BriarWorks - Unsweet Tea - 2018": ["BriarWorks", "Unsweet Tea"],
  "Ashton Old Dog - 2000": ["Ashton", "Old Dog"],
  "Ashton - Celebrated Sovereign - 1998": ["Ashton", "Celebrated Sovereign"],
  "Ashton Old Dog - 2004": ["Ashton", "Old Dog"],

  # ---------- 4noggins ----------
  "A&C Peterson: PREMIER CRU - C": ["A&C Petersen", "Premier Cru"],
  "Ashton: BLACK PARROT 50g 2003 - C": ["Ashton", "Black Parrot"],
  "Ashton: BRINDLE FLAKE 50g 2003 - C": ["Ashton", "Brindle Flake"],
  "Ashton: CELEBRATED SOVEREIGN 50G 1998 - C": ["Ashton", "Celebrated Sovereign"],
  "Brebbia: CLASSIC ENGLISH MIX No. 80 2012 50g - C": ["Brebbia", "Classic English Mix No. 80"],
  "Butera: BLENDED FLAKE 1997 - C": ["Butera", "Blended Flake"],
  "Butera: DARK STOVED 50g 2017 - C": ["Butera", "Dark Stoved"],
  "Butera: GOLDEN CAKE 50g 2017 - C": ["Butera", "Golden Cake"],
  "Butera: MATURED RIBBON 50g 2017 - C": ["Butera", "Matured Ribbon"],
  "Butera: PELICAN 2014 2oz - C": ["Butera", "Pelican"],
  "CAO: MOONTRANCE 50g 2011 - C": ["CAO", "Moontrance"],
  "Capstan: FLAKE GOLD 50g 2013 - C": ["Capstan", "Flake Gold"],
  "Capstan: NAVY CUT MILD 50g 1999 - C": ["Capstan", "Navy Cut Mild"],
  "Cornell & Diehl: PENNINGTON GAP 50g 1998 - C": ["Cornell & Diehl", "Pennington Gap"],
  "Cornell & Diehl: RENAISSANCE da VINCI 50g -2000 - C": ["Cornell & Diehl", "Renaissance da Vinci"],
  "Cornell & Diehl: Small Batch: CAROLINA RED FLAKE 2020 2oz - C": ["Cornell & Diehl", "Carolina Red Flake"],
  "Cornell & Diehl: Small Batch: CAROLINA RED FLAKE 2oz 2016 -C": ["Cornell & Diehl", "Carolina Red Flake"],
  "Cornell & Diehl: Small Batch: CAROLINA RED FLAKE 2oz 2018 -C": ["Cornell & Diehl", "Carolina Red Flake"],
  "Cornell & Diehl: Small Batch: STRAIGHT UP ENGLISH 2oz 2016 -C": ["Cornell & Diehl", "Straight Up English"],
  "Cornell & Diehl: Small Batch: THE BEAST 2oz 2021 - C": ["Cornell & Diehl", "The Beast"],
  "Cornell & Diehl: VINTAGE BLEND-STRATHSPEY 2002 - C": ["Cornell & Diehl", "Strathspey"],
  "Cornell & Diehl: WINTERTIME RESERVE TOBOGGAN RUN 2oz 2021 - C": ["Cornell & Diehl", "Wintertime Reserve Toboggan Run"],
  "Dobie's: FOUR SQUARE 1972 50g- C": ["Dobie's", "Four Square"],
  "Dunhill:  MY MIXTURE \"WHITE SPOT\" 50g 1997 - C": ["Dunhill", "My Mixture White Spot"],
  "Dunhill:  MY MIXTURE (10) 50g  1998 - C": ["Dunhill", "My Mixture 10"],
  "Dunhill:  MY MIXTURE (BABY'S BOTTOM) 50g  1997 - C": ["Dunhill", "Baby's Bottom"],
  "Dunhill:  STANDARD MIXTURE MEDIUM 50g 2001 - C": ["Dunhill", "Standard Mixture Medium"],
  "Dunhill:  STANDARD MIXTURE MEDIUM 50g 2005 - C": ["Dunhill", "Standard Mixture Medium"],
  "Dunhill: DARK FLAKE 50g 2018 - C": ["Dunhill", "Dark Flake"],
  "Dunhill: DE LUXE NAVY ROLLS 50g 2018 - C": ["Dunhill", "De Luxe Navy Rolls"],
  "Dunhill: DURBAR 2005 - C": ["Dunhill", "Durbar"],
  "Dunhill: ELIZABETHAN MIXTURE 50g 2017 -C": ["Dunhill", "Elizabethan Mixture"],
  "Dunhill: LONDON MIXTURE  1999 50g - C": ["Dunhill", "London Mixture"],
  "Dunhill: MILD BLEND 50g 1985 - C": ["Dunhill", "Mild Blend"],
  "Dunhill: MY MIXTURE 965 (Bulk) 3.5oz 1994 - C": ["Dunhill", "My Mixture 965"],
  "Dunhill: MY MIXTURE 965 50g 1976 - C": ["Dunhill", "My Mixture 965"],
  "Dunhill: NIGHTCAP 50g 2005 -C": ["Dunhill", "Nightcap"],
  "Dunhill: ROYAL YACHT 50g 2018 - C": ["Dunhill", "Royal Yacht"],
  "Dunhill: THREE YEAR MATURED 100g 1972 - C": ["Dunhill", "Three Years Matured Virginia"],
  "Dunhill: YE OLDE SIGNE 100g 1972 - C": ["Dunhill", "Ye Olde Signe"],
  "Edgeworth: READY RUBBED 1 3-8 oz.  6 Pouches in Display Box": ["Edgeworth", "Ready Rubbed"],
  "Erik Stokkebye: 4th GENERATION 1957 3.5oz 2013 - C": ["Erik Stokkebye", "4th Generation 1957"],
  "Esoterica: AND SO TO BED 2oz - C": ["Esoterica", "And So to Bed"],
  "Esoterica: AND SO TO BED 8oz - C": ["Esoterica", "And So to Bed"],
  "Esoterica: BLACKPOOL 8oz - C": ["Esoterica", "Blackpool"],
  "Esoterica: BRIGHTON 8oz - C": ["Esoterica", "Brighton"],
  "Esoterica: BRIGHTON 8oz-C": ["Esoterica", "Brighton"],
  "Esoterica: DORCHESTER 2oz 2013 - C": ["Esoterica", "Dorchester"],
  "Esoterica: DUNBAR 8oz - C": ["Esoterica", "Dunbar"],
  "Esoterica: MARGATE 2oz - C": ["Esoterica", "Margate"],
  "Esoterica: MARGATE 8oz - C": ["Esoterica", "Margate"],
  "Esoterica: PEMBROKE 8oz -C": ["Esoterica", "Pembroke"],
  "Esoterica: PEMBROKE 8oz-C": ["Esoterica", "Pembroke"],
  "Esoterica: PENZANCE 2oz 2012 -C": ["Esoterica", "Penzance"],
  "Esoterica: PENZANCE 8oz - C": ["Esoterica", "Penzance"],
  "Esoterica: RAMSGATE 8oz - C": ["Esoterica", "Ramsgate"],
  "Esoterica: ST. IVES 8oz - C": ["Esoterica", "St. Ives"],
  "Esoterica: STONEHAVEN 2oz - C": ["Esoterica", "Stonehaven"],
  "Esoterica: STONEHAVEN 8oz 2017 - C": ["Esoterica", "Stonehaven"],
  "Esoterica: STONEHAVEN 8oz 2018 - C": ["Esoterica", "Stonehaven"],
  "Esoterica: TILBURY 2oz  - C": ["Esoterica", "Tilbury"],
  "Esoterica: TILBURY 2oz - C": ["Esoterica", "Tilbury"],
  "Esoterica: TILBURY 8oz. 2018 - C": ["Esoterica", "Tilbury"],
  "Esoterica: WOODBRIDGE 8oz -C": ["Esoterica", "Woodbridge"],
  "Fribourg & Treyer: CUT BLENDED PLUG 50g 2004 - C": ["Fribourg & Treyer", "Cut Blended Plug"],
  "Fribourg & Treyer: CUT VIRGINIA PLUG 50g 2000 - C": ["Fribourg & Treyer", "Cut Virginia Plug"],
  "Fribourg & Treyer: GOLDEN MIXTURE 50g 2015 - C": ["Fribourg & Treyer", "Golden Mixture"],
  "Fribourg & Treyer: VINTAGE FLAKE 50g 2004 - C": ["Fribourg & Treyer", "Vintage Flake"],
  "G. L. Pease: ARAGORN 2004 - C": ["G.L. Pease", "Aragorn"],
  "G. L. Pease: BARBARY COAST 2oz 2001 - C": ["G.L. Pease", "Barbary Coast"],
  "G. L. Pease: BOHEMIAN SCANDAL 2oz 2004 - C": ["G.L. Pease", "Bohemian Scandal"],
  "G. L. Pease: BOHEMIAN SCANDAL 8oz 2004 - C": ["G.L. Pease", "Bohemian Scandal"],
  "G. L. Pease: INVASION 2oz 2016 - C": ["G.L. Pease", "Invasion"],
  "G. L. Pease: MONTGOMERY 2oz 2005 - C": ["G.L. Pease", "Montgomery"],
  "G. L. Pease: RENAISSANCE 2oz 2004 - C": ["G.L. Pease", "Renaissance"],
  "G. L. Pease: TELEGRAPH HILL 2005 - C": ["G.L. Pease", "Telegraph Hill"],
  "G.L. Pease Fellowship II 20z 2007 - C": ["G.L. Pease", "Fellowship II"],
  "G.L. Pease: ABINGDON 2oz 2007 - C": ["G.L. Pease", "Abingdon"],
  "G.L. Pease: CUMBERLAND 8oz 2004 - C": ["G.L. Pease", "Cumberland"],
  "G.L. Pease: GOBLIN WEED GRAY 2oz 2014 - C": ["G.L. Pease", "Goblin Weed Gray"],
  "G.L. Pease: HADDO'S DELIGHT 2oz 2006 - C": ["G.L. Pease", "Haddo's Delight"],
  "G.L. Pease: MEPHISTO 2oz 2004 - C": ["G.L. Pease", "Mephisto"],
  "G.L. Pease: ODYSSEY 2oz - 2004": ["G.L. Pease", "Odyssey"],
  "G.L. Pease: ODYSSEY 8oz 2015 - C": ["G.L. Pease", "Odyssey"],
  "G.L. Pease: RAVEN'S WING 2oz. 2004 - C": ["G.L. Pease", "Raven's Wing"],
  "G.L. Pease: ROBUSTO 2oz 2003 - C": ["G.L. Pease", "Robusto"],
  "G.L. Pease: SMAUGWEED 2oz 2003 - C": ["G.L. Pease", "Smaugweed"],
  "G.L. Pease: STONEHENGE FLAKE 2oz 2017- C": ["G.L. Pease", "Stonehenge Flake"],
  "G.L. Pease: VAROOM 2oz 2015 - C": ["G.L. Pease", "Varoom"],
  "G.L. Pease: WIZARDS LEAF BLACK 2005 - C": ["G.L. Pease", "Wizards Leaf Black"],
  "G.L. Pease: WIZARDS LEAF WHITE - 2005": ["G.L. Pease", "Wizards Leaf White"],
  "Gawith Hoggarth: BRIGHT CR BURNT ENDS 500g - C": ["Gawith & Hoggarth", "Bright CR Burnt Ends"],
  "Hearth & Home: OLD KINDERHOOK 8oz": ["Hearth & Home", "Old Kinderhook"],
  "Hermit Tobacco: SYRIAN CAKE 8oz 1998 - C": ["Hermit Tobacco", "Syrian Cake"],
  "J.F. Germain: B.K. FLAKE 50g - C": ["J.F. Germain", "B.K. Flake"],
  "J.F. Germain: BRIDGE OLD BROWN FLAKE 50g -C": ["J.F. Germain", "Bridge Old Brown Flake"],
  "J.F. Germain: BROWN FLAKE 50g 2004 - C": ["J.F. Germain", "Brown Flake"],
  "J.F. Germain: CENTURY 50g - C": ["J.F. Germain", "Century"],
  "J.F. Germain: CLUB MIXTURE 50g - C": ["J.F. Germain", "Club Mixture"],
  "J.F. Germain: EIGHTEEN TWENTY 50g -C": ["J.F. Germain", "Eighteen Twenty"],
  "J.F. Germain: FULL LATAKIA 50g - C": ["J.F. Germain", "Full Latakia"],
  "J.F. Germain: KING CHARLES MIXTURE 50g - C": ["J.F. Germain", "King Charles Mixture"],
  "J.F. Germain: MEDIUM FLAKE 50g - C": ["J.F. Germain", "Medium Flake"],
  "J.F. Germain: RICH DARK FLAKE 50g - C": ["J.F. Germain", "Rich Dark Flake"],
  "J.F. Germain: ROYAL JERSEY w-LATAKIA 50g 2016 - C": ["J.F. Germain", "Royal Jersey Latakia"],
  "J.F. Germain: ROYAL JERSEY w-PERIQUE 50g 2016 - C": ["J.F. Germain", "Royal Jersey Perique"],
  "J.F. Germain: SPECIAL LATAKIA FLAKE 2015 - C": ["J.F. Germain", "Special Latakia Flake"],
  "J.F. Germain: UNCLE TOM'S SMOKING MIXTURE 50g - C": ["J.F. Germain", "Uncle Tom's Smoking Mixture"],
  "John Cotton's: SMYRNA 1.75oz 2018 - C": ["John Cotton's", "Smyrna"],
  "John Sinclair: READY RUBBED VIRGINIA 50g 1991 - C": ["John Sinclair", "Ready Rubbed Virginia"],
  "Kohlhasse: MASTRO DE PAJA ROMA 50g - C": ["Mastro de Paja", "Roma"],
  "Levin Pipes: VIRGINIA WOODS 1988 4oz. - C": ["Levin Pipes", "Virginia Woods"],
  "Mac Baren: BURLEY LONDON BLEND 100g 1976- C": ["Mac Baren", "Burley London Blend"],
  "Mac Baren: HH ACADIAN PERIQUE 100g 2020 - C": ["Mac Baren", "HH Acadian Perique"],
  "Mac Baren: HH MATURE VIRGINIA 100g 2010 - C": ["Mac Baren", "HH Mature Virginia"],
  "Mac Baren: HH VINTAGE SYRIAN 1.75oz 2017 - C": ["Mac Baren", "HH Vintage Syrian"],
  "Mac Baren: HH VINTAGE SYRIAN 100g 2017 - C": ["Mac Baren", "HH Vintage Syrian"],
  "Mac Baren: MODERN VIRGINIA LOOSE CUT 100g 2014 - C": ["Mac Baren", "Modern Virginia Loose Cut"],
  "Mac Baren: PLUMCAKE 3.5oz 2012 - C": ["Mac Baren", "Plumcake"],
  "Mac Baren: ROLL CAKE 3.5oz 2013 - C": ["Mac Baren", "Roll Cake"],
  "Mac Baren: UNCUT NAVY FLAKE PLUG 100g - C": ["Mac Baren", "Uncut Navy Flake Plug"],
  "McClelland Bulk: 2020: MATURED CAKE 2oz 2017 - C": ["McClelland", "2020 Matured Cake"],
  "McClelland Bulk: 5125 COYOTE CLASSIC FULL 2oz 2017 - C": ["McClelland", "5125 Coyote Classic Full"],
  "McClelland: 40TH ANNIVERSARY 100g - C": ["McClelland", "40th Anniversary"],
  "McClelland: 5100: RED CAKE 2.5oz Jar 2012 - C": ["McClelland", "5100 Red Cake"],
  "McClelland: ANNIVERSARY - 2005 - C": ["McClelland", "Anniversary"],
  "McClelland: ARCADIA 50g 2005 -C": ["McClelland", "Arcadia"],
  "McClelland: BALKAN BEAUTY 50g 2016 - C": ["McClelland", "Balkan Beauty"],
  "McClelland: BEACON 50g 2015 - C": ["McClelland", "Beacon"],
  "McClelland: BEACON EXTRA 50g 2017 - C": ["McClelland", "Beacon Extra"],
  "McClelland: BERKEBILE II SPECIAL RESERVE 50g 2005 - C": ["McClelland", "Berkebile II Special Reserve"],
  "McClelland: BLACK SHAG 50g 1999 - C": ["McClelland", "Black Shag"],
  "McClelland: BOSTON 1776 50g 2010 - C": ["McClelland", "Boston 1776"],
  "McClelland: Boston 1776 Va. Flake 1993 - C": ["McClelland", "Boston 1776"],
  "McClelland: CELEBRATED SOVEREIGN 50g 2011 - C": ["McClelland", "Celebrated Sovereign"],
  "McClelland: CHRISTMAS CHEER 100g 2009 - C": ["McClelland", "Christmas Cheer"],
  "McClelland: CHRISTMAS CHEER 100g 2010 - C": ["McClelland", "Christmas Cheer"],
  "McClelland: CHRISTMAS CHEER 100g 2011 - C": ["McClelland", "Christmas Cheer"],
  "McClelland: CHRISTMAS CHEER 100g 2017 - C": ["McClelland", "Christmas Cheer"],
  "McClelland: CPCC RICH VIRGINIA RIBBON 50g 2015 - C": ["McClelland", "CPCC Rich Virginia Ribbon"],
  "McClelland: DEEP HOLLOW 100g 2017 - C": ["McClelland", "Deep Hollow"],
  "McClelland: FROG MORTON'S CELLAR 50g 2013 - C": ["McClelland", "Frog Morton's Cellar"],
  "McClelland: NAVY CAVENDISH 100g 2015 - C": ["McClelland", "Navy Cavendish"],
  "McClelland: NAVY CAVENDISH 100g 2017 - C": ["McClelland", "Navy Cavendish"],
  "McClelland: NO. 27 MATURED VIRGINIA  50g 2011 - C": ["McClelland", "No. 27 Matured Virginia"],
  "McClelland: OLD DOG 50g 2011 - C": ["McClelland", "Old Dog"],
  "McClelland: PAL O' MINE 50g 2017 - C": ["McClelland", "Pal O' Mine"],
  "McClelland: PERSONAL RESERVE TROLLSHAWS 100g 1991 - C": ["McClelland", "Personal Reserve Trollshaws"],
  "McClelland: RED AND BLACK 50g 2017 - C": ["McClelland", "Red and Black"],
  "McClelland: ROYAL CAJUN EBONY 2006 - C": ["McClelland", "Royal Cajun Ebony"],
  "McClelland: ROYAL CAJUN SPECIAL 50g 2006 -C": ["McClelland", "Royal Cajun Special"],
  "McClelland: ST. JAMES WOODS 50g 2015 - C": ["McClelland", "St. James Woods"],
  "McClelland: STAVE-AGED VIRGINIA RIBBON 35 50g 2017 - C": ["McClelland", "Stave-Aged Virginia Ribbon 35"],
  "McClelland: TUDOR CASTLE 50g 2017 - C": ["McClelland", "Tudor Castle"],
  "McClelland: WILDERNESS 50g 2010 - C": ["McClelland", "Wilderness"],
  "McClelland: YENIDJE HIGHLANDER 2011 50g - C": ["McClelland", "Yenidje Highlander"],
  "McClelland: YENIDJE HIGHLANDER 2012 50g - C": ["McClelland", "Yenidje Highlander"],
  "McCranie's:  RED RIBBON 50g 2005 - C": ["McCranie's", "Red Ribbon"],
  "McCranie's: RED FLAKE 50g 1994 - C": ["McCranie's", "Red Flake"],
  "McCranie's: RED FLAKE 50g 2012 - C": ["McCranie's", "Red Flake"],
  "McCranie's: RED RIBBON 1999 - C": ["McCranie's", "Red Ribbon"],
  "McCranie's: TOM'S PRIVATE RESERVE 4oz 2012 - C": ["McCranie's", "Tom's Private Reserve"],
  "Nording: Hunter Blend: BEAGLE 1.75oz - C": ["Nording", "Hunter Blend Beagle"],
  "Nording: Hunter Blend: POINTER 50g 2017 - C": ["Nording", "Hunter Blend Pointer"],
  "Peterson: UNIVERSITY FLAKE 2007 - C": ["Peterson", "University Flake"],
  "Peterson: UNIVERSITY FLAKE 50g 2015 - C": ["Peterson", "University Flake"],
  "Robert Lewis: TREE MIXTURE 50g 2011 - C": ["Robert Lewis", "Tree Mixture"],
  "Robert McConnell: BLACK & GOLD 50g 2009 - C": ["Robert McConnell", "Black & Gold"],
  "Robert McConnell: RED VIRGINIA 50g 2009 - C": ["Robert McConnell", "Red Virginia"],
  "Robert McConnell: SCOTTISH FLAKE 50g 2007 - C": ["Robert McConnell", "Scottish Flake"],
  "Samuel Gawith: BROWN No. 4 50g 2004 - C": ["Samuel Gawith", "Brown No. 4"],
  "Samuel Gawith: BROWN No. 4 50g 2011 - C": ["Samuel Gawith", "Brown No. 4"],
  "Samuel Gawith: CABBIE'S MIXTURE 50g 2018 - C": ["Samuel Gawith", "Cabbie's Mixture"],
  "Samuel Gawith: COMMONWEALTH MIXTURE 50g 2003 - C": ["Samuel Gawith", "Commonwealth Mixture"],
  "Samuel Gawith: NAVY FLAKE 50g 2016 - C": ["Samuel Gawith", "Navy Flake"],
  "Samuel Gawith: SQUADRON LEADER w- Perique 50g - C": ["Samuel Gawith", "Squadron Leader Perique"],
  "Samuel Gawith: ST. JAMES FLAKE 50g 2018 -C": ["Samuel Gawith", "St. James Flake"],
  "Samuel Gawith: ST. JAMES MINI PLUG 8oz - C": ["Samuel Gawith", "St. James Mini Plug"],
  "Smoker's Haven: 20th Anniversary Mixture 2oz 2012 - C": ["Smoker's Haven", "20th Anniversary Mixture"],
  "Smoker's Haven: IN-B-TWEEN MIXTURE 2oz 2018 - C": ["Smoker's Haven", "In-B-Tween Mixture"],
  "Smoker's Haven: SELECT MIXTURE 2oz 2018 - C": ["Smoker's Haven", "Select Mixture"],
  "Solani: 633 VIRGINIA FLAKE 50g 2008 - C": ["Solani", "633 Virginia Flake"],
  "St. Bruno: ST BRUNO FLAKE 50g 1992 - C": ["St. Bruno", "Flake"],
  "Sutliff: SWEATED 12oz 2025 - C": ["Sutliff", "Sweated"],
  "The Smoker Ltd.: FAVORITE 50g 1992 - C": ["The Smoker Ltd.", "Favorite"],
  "W.O. Larsen: EDITION 2009 100g - C": ["W.O. Larsen", "Edition 2009"],
  "W.O. Larsen: EDITION 2011 100g - C": ["W.O. Larsen", "Edition 2011"],
  "W.O. Larsen: EDITION 2012 100g - C": ["W.O. Larsen", "Edition 2012"],
  "W.O. Larsen: OLD FASHIONED 100g 2012 - C": ["W.O. Larsen", "Old Fashioned"],
  "Wessex: BRIGADE CAMPAIGN DARK FLAKE 50g 2016 - C": ["Wessex", "Brigade Campaign Dark Flake"],
  "Wessex: BRIGADE SOVEREIGN CURLY CUT 50g 2018 - C": ["Wessex", "Brigade Sovereign Curly Cut"],
  "Wessex: BROWN VIRGINIA FLAKE 50g 2012 - C": ["Wessex", "Brown Virginia Flake"],
  "Wessex: BURLEY SLICE 50g 2014 - C": ["Wessex", "Burley Slice"],
  "Wessex: GOLD SLICE 1.5oz 2017 - C": ["Wessex", "Gold Slice"],
  "Balkan Sobranie: BALKAN SOBRANIE 50g -C": ["Balkan Sobranie", "Balkan Sobranie"],
  "Esoterica: DUNBAR 2oz - C": ["Esoterica", "Dunbar"],
  "Esoterica: PEMBROKE 2oz - C": ["Esoterica", "Pembroke"],
  "Esoterica: PENZANCE 50g - C": ["Esoterica", "Penzance"],
  "Esoterica: TILBURY 8oz - C": ["Esoterica", "Tilbury"],
  "J.F. Germain: PLUM CAKE MIXTURE 1.76oz - C": ["J.F. Germain", "Plum Cake Mixture"],
  "J.F. Germain: SPECIAL LATAKIA FLAKE - C": ["J.F. Germain", "Special Latakia Flake"],
  "McClelland: DARK STAR 50g 2011 - C": ["McClelland", "Dark Star"],
  "McClelland: FROG MORTON 50g 2017 - C": ["McClelland", "Frog Morton"],
  "Smoker's Haven: OUR BEST BLEND 2oz 2018 - C": ["Smoker's Haven", "Our Best Blend"],
  "Smokers' Haven: EXOTIQUE MIXTURE 2oz 2018 - C": ["Smoker's Haven", "Exotique Mixture"],
  "Sutliff: CRINGLE FLAKE 1.5oz 2020 - C": ["Sutliff", "Cringle Flake"],
  "Solani: 656 AGED BURLEY FLAKE 50g 2011 - C": ["Solani", "656 Aged Burley Flake"],
  "Solani: 656 AGED BURLEY FLAKE 50g 2018 - C": ["Solani", "656 Aged Burley Flake"],
}


def main():
    overrides = json.load(open(os.path.join(HERE, "overrides.json"), encoding="utf-8"))
    titles = []
    for f in SRC:
        d = json.load(open(os.path.join(DOCS, f), encoding="utf-8"))
        for p in d.get("products", []):
            n = (p.get("name") or "").strip()
            if n:
                titles.append(n)
    titles = list(dict.fromkeys(titles))  # unique, order-preserving

    cache = {}
    missing = []
    for t in titles:
        if t in overrides:
            r = {"brand": "", "blend": "", "is_tin": True, "confidence": 1.0}
            r.update(overrides[t])
            r["source"] = "override"
            cache[t] = r
        elif t in EXTRACT:
            v = EXTRACT[t]
            cache[t] = {"brand": v[0], "blend": v[1],
                        "is_tin": v[2] if len(v) > 2 else True,
                        "confidence": 0.9, "source": "llm"}
        else:
            missing.append(t)

    unused = [k for k in EXTRACT if k not in titles]

    with open(os.path.join(HERE, "blend_cache.json"), "w", encoding="utf-8") as fh:
        json.dump(cache, fh, ensure_ascii=False, indent=2, sort_keys=True)

    print(f"catalog titles: {len(titles)}   cached: {len(cache)}")
    print(f"MISSING (no extraction — will fall back to standalone): {len(missing)}")
    for t in missing:
        print("   MISS:", repr(t))
    print(f"UNUSED extract keys (typo'd, matched nothing): {len(unused)}")
    for t in unused:
        print("   UNUSED:", repr(t))


if __name__ == "__main__":
    main()
